In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
import torch
from sklearn.metrics import accuracy_score, f1_score
from transformers import Trainer, TrainingArguments
from transformers import AutoTokenizer, BertForSequenceClassification
from datasets import load_dataset, Dataset

2025-02-28 11:29:34.855745: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-28 11:29:34.870512: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740722374.889622  488347 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740722374.896049  488347 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-28 11:29:34.915988: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
df_train = pd.read_csv("Train_title.csv", encoding = 'utf-8')

In [3]:
df_train.head(10)

   news_category                                         news_title
0     Tamil Nadu  மாவோயிஸ்ட் தாக்குதலில் வீரமரணம் : துப்பாக்கி க...
1     Tamil Nadu  காஞ்சிபுரத்தில் இன்று அதிகாலை மளிகை கடை குடோனி...
2         Cinema                                       கிளிப்பிங்ஸ்
3          World                     அமெரிக்காவின் டெக்சாஸ் மாகாணம்
4         Sports  விளையாட்டு அமைச்சகம் பரிந்துரை பி.வி.சிந்துவுக...
5          Crime  எழும்பூரில் உள்ள வணிக வளாகத்தில் 14 கடைகளை உடை...
6         Sports                              டோனியுடன் உரசல் இல்லை
7  District News           தொன்னாடு ஊராட்சியில் வங்கி தலைவர் தேர்வு
8          India                    நடிகை வீட்டில் கள்ள நோட்டுக்கள்
9     Tamil Nadu  ஜனநாயக உரிமையை காலில் போட்டு ஜெயலலிதா அரசு மித...

In [4]:
df_train.dtypes

news_category    object
news_title       object
dtype: object

In [5]:
df_test = pd.read_csv("Test_title.csv", encoding = 'utf-8')

In [6]:
df_test.head(10)

   news_category                                         news_title
0         Sports  இந்தியர்களுக்கு  ‘கிரிக்கெட்டிஸ்’ நோய்:   ராம்...
1          World  நைஜீரிய தீவிரவாதிகள் அட்டகாசம் துப்பாக்கி சூட்...
2          India  அரசியலில் இருந்து மோடியை  விரட்டும் வரை ஓயமாட்...
3         Sports  ‘டெஸ்ட் கிரிக்கெட்தான் சவாலானது’: ராகுல் டிராவ...
4          World  பாகிஸ்தானில் பரபரப்பு அதிபர் ஒபாமா படம் போட்ட ...
5         Cinema                 டால்பினை தத்தெடுத்தார் எமி ஜாக்ஸன்
6         Cinema                 பிரதமர் விருந்து:  தனுஷ் மகிழ்ச்சி
7          World  தமிழர் வசிக்கும் பகுதியில் அடுத்த ஆண்டில் தேர்...
8         Sports  ஏஎப்சி கோப்பை பைனலில் பெங்களூரு மற்ற போட்டிகளை...
9  District News  மதுராந்தகம் அருகே இன்ஜினியரிங் கல்லூரி மாணவர் ...

In [7]:
df_test

       news_category                                         news_title
0             Sports  இந்தியர்களுக்கு  ‘கிரிக்கெட்டிஸ்’ நோய்:   ராம்...
1              World  நைஜீரிய தீவிரவாதிகள் அட்டகாசம் துப்பாக்கி சூட்...
2              India  அரசியலில் இருந்து மோடியை  விரட்டும் வரை ஓயமாட்...
3             Sports  ‘டெஸ்ட் கிரிக்கெட்தான் சவாலானது’: ராகுல் டிராவ...
4              World  பாகிஸ்தானில் பரபரப்பு அதிபர் ஒபாமா படம் போட்ட ...
...              ...                                                ...
12802         Sports               பாக்.கை சுருட்டியது : பைனலில் இலங்கை
12803          Crime  குடியிருப்புகளுக்கு மத்தியில் இயங்கிய போலி மது...
12804  District News  பாமக நிர்வாகியை கொல்ல முயற்சி போலீசில் தம்பி ப...
12805          Crime       ஜி.ஹெச்சில் ரவுடி கொலை : 8 பேர் கும்பல் கைது
12806         Cinema                   அஞ்சலி நடித்த படத்துக்கு சிக்கல்

[12807 rows x 2 columns]

In [8]:
df_test['news_title'][6]

'பிரதமர் விருந்து:  தனுஷ் மகிழ்ச்சி'

In [9]:
classes = set(df_train['news_category'].values)
display(classes)

{'Cinema', 'Crime', 'District News', 'India', 'Sports', 'Tamil Nadu', 'World'}

In [10]:
label_mapping = {category: code for code, category in enumerate(sorted(set(df_train['news_category'].values)))}
print(label_mapping)

{'Cinema': 0, 'Crime': 1, 'District News': 2, 'India': 3, 'Sports': 4, 'Tamil Nadu': 5, 'World': 6}

In [11]:
df_train['label'] = df_train['news_category'].map(label_mapping)
df_test['label'] = df_test['news_category'].map(label_mapping)

In [12]:
df_train.columns

Index(['news_category', 'news_title', 'label'], dtype='object')

In [13]:
df_train[['news_category', 'label']].head(5)

  news_category  label
0    Tamil Nadu      5
1    Tamil Nadu      5
2        Cinema      0
3         World      6
4        Sports      4

In [15]:
df_train = df_train[['news_title', 'label']]
df_test = df_test[['news_title', 'label']]

In [16]:
df_train.columns

Index(['news_title', 'label'], dtype='object')

In [17]:
classes_num = df_train['label'].nunique()
ds_t = Dataset.from_pandas(df_train)
ds_v = Dataset.from_pandas(df_test)

In [22]:
import torch
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, BertForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score
import os

# Model training parameters
max_sequence_length = 64
epochs = 5
batch_size = 64
save_steps = 1000

def set_seed(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

# Training function
def train_model(model_name):
    log_file = f"{model_name}_results.csv"
    
    # Initialize logging
    with open(log_file, 'w') as f:
        f.write("Model,Accuracy,F1\n")
    
    print(f"\nTraining Model: {model_name}")
    
    # Set seed for reproducibility
    set_seed(42)

    # Load tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = BertForSequenceClassification.from_pretrained(model_name, num_labels=classes_num).to('cuda')
    
    # Preprocessing function
    def preprocess_function(examples):
        return tokenizer(examples['news_title'], truncation=True, padding="max_length", max_length=max_sequence_length)

    dataset_train = ds_t.map(preprocess_function, batched=True)
    dataset_validation = ds_v.map(preprocess_function, batched=True)

    # Compute accuracy and F1-score, and track misclassified samples
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        acc = accuracy_score(labels, predictions)
        f1 = f1_score(labels, predictions, average='macro')
        

        # Identify misclassified samples
        misclassified_samples = pd.DataFrame({
            "News_Article": ds_v["news_title"],
            "True_Label": labels,
            "Predicted_Label": predictions
        })[labels != predictions]

        # Tokenize misclassified samples for analysis
        tokenized_output = tokenizer(misclassified_samples["News_Article"].tolist(), 
                                     padding=True, truncation=True, 
                                     max_length=max_sequence_length, return_tensors="pt")

        # Convert token IDs to actual tokens
        misclassified_samples["Tokenized_Article"] = [
            " ".join(tokenizer.convert_ids_to_tokens(token_ids)) 
            for token_ids in tokenized_output["input_ids"].tolist()
        ]

        # Ensure the directory exists
        output_dir = f"misclassified_{model_name}"
        os.makedirs(output_dir, exist_ok=True)

        # Save misclassified samples
        misclassified_samples.to_csv(f"{output_dir}/misclassified.csv", index=False)

        # Log results
        with open(log_file, 'a') as f:
            f.write(f"{model_name},{acc:.4f},{f1:.4f}\n")

        return {'accuracy': acc, 'f1_score': f1}

    # Training arguments
    training_args = TrainingArguments(
        output_dir=f"{model_name}_output/", overwrite_output_dir=True, num_train_epochs=epochs,
        per_device_train_batch_size=batch_size, per_device_eval_batch_size=batch_size, save_steps=save_steps,
        save_total_limit=1,fp16=True,learning_rate=1e-4,logging_steps=50,evaluation_strategy="steps",
        eval_steps=50,seed=42  # Set the seed for reproducibility
    )

    # Trainer
    trainer = Trainer(model=model,args=training_args,
        train_dataset=dataset_train,eval_dataset=dataset_validation,compute_metrics=compute_metrics
    )

    # Train model
    trainer.train()
    print(f"Training completed for model: {model_name}\n")

In [23]:
train_model('bert_wordpiece/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_wordpiece/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_wordpiece/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Training completed for model: bert_wordpiece/

In [24]:
train_model('bert_wordpiece_50000/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_wordpiece_50000/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_wordpiece_50000/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Training completed for model: bert_wordpiece_50000/

In [25]:
train_model('bert_senpiece/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_senpiece/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_senpiece/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Training completed for model: bert_senpiece/

In [26]:
train_model('bert_senpiece_50000/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_senpiece_50000/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_senpiece_50000/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Training completed for model: bert_senpiece_50000/

In [29]:
import torch
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, BertForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score
import os


# Model training parameters
max_sequence_length = 64
epochs = 5
batch_size = 64
save_steps = 1000

    
def set_seed(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

# Training function
def train_model(model_name):
    print(f"\nTraining Model: {model_name}")
    
    log_file = f"{model_name}_results.csv"
    
    # Initialize logging
    with open(log_file, 'w') as f:
        f.write("Model,Accuracy,F1\n")
    
     # Set seed for reproducibility
    set_seed(42)

    # Load tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = BertForSequenceClassification.from_pretrained(model_name, num_labels=classes_num).to('cuda')
    
    # Preprocessing function
    def preprocess_function(examples):
        return tokenizer(examples['news_title'], truncation=True, padding="max_length", max_length=max_sequence_length)

    dataset_train = ds_t.map(preprocess_function, batched=True)
    dataset_validation = ds_v.map(preprocess_function, batched=True)

    # Compute accuracy and F1-score, and track misclassified samples
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        acc = accuracy_score(labels, predictions)
        f1 = f1_score(labels, predictions, average='macro')

    # Identify misclassified samples
        misclassified_samples = pd.DataFrame({
        "News_Article": ds_v["news_title"],
        "True_Label": labels,
        "Predicted_Label": predictions
         })[labels != predictions]

    # Tokenize misclassified samples for analysis
        tokenized_output = tokenizer(misclassified_samples["News_Article"].tolist(), 
                                 padding=True, truncation=True, 
                                 max_length=max_sequence_length, return_tensors="pt")

    # Convert token IDs to actual tokens
       # Convert token IDs to actual readable Tamil text
        misclassified_samples["Decoded_Article"] = [
                              tokenizer.decode(token_ids, skip_special_tokens=True)  
                               for token_ids in tokenized_output["input_ids"].tolist()
                                 ]


    # Ensure the directory exists
        output_dir = f"misclassified_{model_name}"
        os.makedirs(output_dir, exist_ok=True)

    # Save misclassified samples
        misclassified_samples.to_csv(f"{output_dir}/misclassified.csv", index=False)

    # Log results
        with open(log_file, 'a') as f:
            f.write(f"{model_name},{acc},{f1}\n")

        return {'accuracy': acc, 'f1_score': f1}



    # Training arguments
    training_args = TrainingArguments(
        output_dir=f"{model_name}_output/",
        overwrite_output_dir=True,
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        save_steps=save_steps,
        save_total_limit=1,
        fp16=True,
        learning_rate=1e-4,
        logging_steps=50,
        evaluation_strategy="steps",
        eval_steps=50,
        seed=42  # Set the seed for reproducibility
    )

    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset_train,
        eval_dataset=dataset_validation,
        compute_metrics=compute_metrics
    )

    # Train model
    trainer.train()

In [30]:
train_model('bert_bbpe/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_bbpe/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_bbpe/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [31]:
train_model('bert_bbpe_50000/')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert_bbpe_50000/ and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Training Model: bert_bbpe_50000/

Map:   0%|          | 0/51227 [00:00<?, ? examples/s]

Map:   0%|          | 0/12807 [00:00<?, ? examples/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [19]:
from transformers import BertTokenizer

# Load the pre-trained WordPiece tokenizer (BERT tokenizer in this case)
tokenizer = tokenizer = AutoTokenizer.from_pretrained('bert_bbpe/')

# Your Tamil text
text = 'பிரதமர் விருந்து:  தனுஷ் மகிழ்ச்சி'

# Tokenize the text
tokens = tokenizer.tokenize(text)

# Print the tokenized output and the length of the sequence
print(f"Tokenized Text: {tokens}")
print(f"Number of Tokens: {len(tokens)}")

# Check if it's within the limit (64 tokens)
if len(tokens) > 64:
    print("The sequence is too long and needs to be truncated or split.")
else:
    print("The sequence length is within the limit.")

Tokenized Text: ['à®ª', 'à®¿', 'à®°à®¤à®®à®°', 'à¯į', 'Ġà®µ', 'à®¿', 'à®°', 'à¯ģ', 'à®¨', 'à¯į', 'à®¤', 'à¯ģ:', 'Ġ', 'Ġà®¤à®©', 'à¯ģ', 'à®·', 'à¯į', 'Ġà®®à®ķ', 'à®¿', 'à®´', 'à¯į', 'à®ļ', 'à¯į', 'à®ļ', 'à®¿']
Number of Tokens: 25
The sequence length is within the limit.